CREATE DATABASE MedPlants;

USE MedPlants;

CREATE TABLE USUARIOS (
	ID_USER INT NOT NULL AUTO_INCREMENT,
	CPF_USER VARCHAR(11) NOT NULL UNIQUE,
	NOME_USER VARCHAR(50) NOT NULL,
	SOBRENOME_USER VARCHAR(50) NOT NULL,
	EMAIL_USER VARCHAR(50) NOT NULL,
	SENHA_USER VARCHAR(15) NOT NULL,
    CONFIRMAR_SENHA_USER VARCHAR(15) NOT NULL,
	DATA_NASCIMENTO_USER DATE,
	PERGUNTA_SECRETA_USER VARCHAR(200) NOT NULL,
	RESPOSTA_SECRETA_USER TEXT NOT NULL,
	PRIMARY KEY(ID_USER)
);
   
CREATE TABLE SINTOMAS (
	ID_SINT INT NOT NULL AUTO_INCREMENT,
	PALAVRA_CHAVE_SINT VARCHAR(30) NOT NULL,
	DESCRICAO_SINT TEXT NULL,
	PRIMARY KEY(ID_SINT)
);
   
CREATE TABLE ERVAS (
	ID_ERV INT NOT NULL AUTO_INCREMENT,
	NOME_POPULAR_ERV VARCHAR(40) NOT NULL,
	NOME_CIENTIFICO VARCHAR(100) NOT NULL,
	INDICACAO_USO_ERV TEXT NOT NULL,
    CONTRA_INDICACAO_ERV TEXT NOT NULL,
    PROPRIEDADES_ERV TEXT NOT NULL ,
	PRIMARY KEY(ID_ERV)
);

CREATE TABLE UTILIZACAO (
	SINTOMAS_ID_SINT INT NOT NULL,
    ERVAS_ID_ERV INT NOT NULL,
    MODO_PREPARO_ATUA TEXT,
    FOREIGN KEY (SINTOMAS_ID_SINT) REFERENCES SINTOMAS (ID_SINT),
    FOREIGN KEY (ERVAS_ID_ERV) REFERENCES ERVAS (ID_ERV),
    PRIMARY KEY(SINTOMAS_ID_SINT, ERVAS_ID_ERV)
);
  
CREATE TABLE USUARIO_TEM_SINTOMAS (
	USUARIO_TEM_SINTOMAS_ID_USER INT NOT NULL,
    USUARIO_TEM_SINTOMAS_ID_SINT INT NOT NULL,
    FOREIGN KEY (USUARIO_TEM_SINTOMAS_ID_USER) REFERENCES USUARIOS (ID_USER),
    FOREIGN KEY (USUARIO_TEM_SINTOMAS_ID_SINT) REFERENCES SINTOMAS (ID_SINT),
    PRIMARY KEY (USUARIO_TEM_SINTOMAS_ID_USER, USUARIO_TEM_SINTOMAS_ID_SINT)
);

INSERT INTO USUARIOS(CPF_USER, NOME_USER, SOBRENOME_USER, EMAIL_USER, SENHA_USER, CONFIRMAR_SENHA_USER, PERGUNTA_SECRETA_USER, RESPOSTA_SECRETA_USER)
VALUES ("12345678912", "WILLY", "FELIZ", "williane@gmail.com", "123", "123", "quantos anos ce tem?", "80");

